steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-west1-docker.pkg.dev/aicin-477004/aicin-agents/orchestrator:latest'
      - '-f'
      - 'agents/orchestrator/Dockerfile'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-west1-docker.pkg.dev/aicin-477004/aicin-agents/orchestrator:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'orchestrator'
      - '--image'
      - 'us-west1-docker.pkg.dev/aicin-477004/aicin-agents/orchestrator:latest'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'

images:
  - 'us-west1-docker.pkg.dev/aicin-477004/aicin-agents/orchestrator:latest'

timeout: 600s
