/**
 * Google Gemini AI Integration
 * Path enrichment and semantic enhancement using Vertex AI
 */

import { VertexAI } from '@google-cloud/vertexai';
import type { PathMatchResult, LearningPath } from '@aicin/types';

// Initialize Vertex AI
const project = process.env.GOOGLE_CLOUD_PROJECT || 'aicin-477004';
const location = process.env.GOOGLE_CLOUD_LOCATION || 'us-central1';

const vertex_ai = new VertexAI({ project, location });
const model = 'gemini-1.5-flash'; // Updated to Gemini 1.5 Flash (faster, more cost-effective)

/**
 * Enrich learning path with AI-generated insights
 */
export async function enrichPathWithGemini(
  path: LearningPath,
  userInterests: string[],
  userGoals: string
): Promise<{
  enhancedDescription: string;
  matchReasons: string[];
  learningOutcomes: string[];
  prerequisites: string[];
  careerRelevance: string;
}> {
  try {
    const generativeModel = vertex_ai.getGenerativeModel({ model });

    const prompt = `You are an AI learning advisor. Analyze this learning path and provide insights.

Learning Path: ${path.title}
Description: ${path.description || 'No description provided'}
Topics: ${path.topics?.join(', ') || 'No topics listed'}

User Context:
- Interests: ${userInterests.join(', ')}
- Goals: ${userGoals}

Provide a JSON response with:
1. enhancedDescription: A compelling 2-3 sentence description highlighting why this path matches the user's interests
2. matchReasons: Array of 3-5 specific reasons why this path is a good fit
3. learningOutcomes: Array of 3-5 key skills/knowledge the user will gain
4. prerequisites: Array of 2-3 recommended prerequisites or background knowledge
5. careerRelevance: 1-2 sentences on how this relates to career goals

Format as valid JSON only, no markdown.`;

    const result = await generativeModel.generateContent(prompt);
    const response = result.response;
    const text = response.candidates?.[0]?.content?.parts?.[0]?.text || '{}';

    // Parse JSON response
    const enrichment = JSON.parse(text);

    console.log(`[Gemini] Enriched path: ${path.title}`);

    return {
      enhancedDescription: enrichment.enhancedDescription || path.description || '',
      matchReasons: Array.isArray(enrichment.matchReasons) ? enrichment.matchReasons : [],
      learningOutcomes: Array.isArray(enrichment.learningOutcomes) ? enrichment.learningOutcomes : [],
      prerequisites: Array.isArray(enrichment.prerequisites) ? enrichment.prerequisites : [],
      careerRelevance: enrichment.careerRelevance || ''
    };
  } catch (error) {
    console.error(`[Gemini] Enrichment failed for ${path.title}:`, error);

    // Return fallback enrichment
    return {
      enhancedDescription: path.description || '',
      matchReasons: [`Matches interest: ${userInterests[0] || 'general learning'}`],
      learningOutcomes: ['Gain practical skills', 'Build portfolio projects'],
      prerequisites: ['Basic understanding of the subject'],
      careerRelevance: 'Relevant to modern career paths'
    };
  }
}

/**
 * Batch enrich multiple paths
 */
export async function enrichPathsWithGemini(
  paths: PathMatchResult[],
  userInterests: string[],
  userGoals: string,
  maxPaths: number = 3
): Promise<PathMatchResult[]> {
  console.log(`[Gemini] Enriching top ${Math.min(paths.length, maxPaths)} paths`);

  const enrichedPaths: PathMatchResult[] = [];

  // Enrich top N paths only (to save API costs)
  for (let i = 0; i < Math.min(paths.length, maxPaths); i++) {
    const path = paths[i];

    try {
      const enrichment = await enrichPathWithGemini(
        {
          id: path.pathId,
          document_id: `path-${path.pathId}`,
          title: path.pathTitle,
          slug: path.pathSlug,
          description: path.pathTitle, // Use title as fallback description
          topics: [], // Would come from categoryBreakdown
          is_active: true,
          updated_at: new Date()
        },
        userInterests,
        userGoals
      );

      // Add Gemini enrichment to match reasons
      const geminiReasons = enrichment.matchReasons.slice(0, 3);

      enrichedPaths.push({
        ...path,
        matchReasons: [
          ...path.matchReasons,
          ...geminiReasons.map(reason => ({
            reason,
            category: 'ai-insight',
            weight: 1.0,
            evidence: 'Generated by Gemini AI'
          }))
        ]
        // Note: Gemini enrichment details available in learningOutcomes and matchReasons
      });
    } catch (error) {
      console.error(`[Gemini] Failed to enrich path ${path.pathId}:`, error);
      // Include path without enrichment
      enrichedPaths.push(path);
    }
  }

  // Add remaining paths without enrichment
  enrichedPaths.push(...paths.slice(maxPaths));

  return enrichedPaths;
}

/**
 * Generate personalized learning advice
 */
export async function generateLearningAdvice(
  userProfile: {
    interests: string[];
    goals: string;
    experienceLevel: string;
  },
  topPaths: PathMatchResult[]
): Promise<string> {
  try {
    const generativeModel = vertex_ai.getGenerativeModel({ model });

    const pathSummaries = topPaths.slice(0, 3).map(p =>
      `- ${p.pathTitle} (match score: ${p.matchScore})`
    ).join('\n');

    const prompt = `You are an AI learning advisor. Provide personalized guidance.

User Profile:
- Interests: ${userProfile.interests.join(', ')}
- Goals: ${userProfile.goals}
- Experience Level: ${userProfile.experienceLevel}

Recommended Paths:
${pathSummaries}

Provide a brief (2-3 sentences) personalized learning recommendation that:
1. Acknowledges their interests and goals
2. Explains why these paths are a good fit
3. Offers one actionable next step

Be encouraging and specific. Write in second person ("you").`;

    const result = await generativeModel.generateContent(prompt);
    const response = result.response;
    const advice = response.candidates?.[0]?.content?.parts?.[0]?.text || '';

    console.log(`[Gemini] Generated learning advice`);

    return advice;
  } catch (error) {
    console.error(`[Gemini] Failed to generate advice:`, error);
    return 'Based on your interests, these recommended paths will help you build valuable skills. Start with the top-ranked path and focus on hands-on projects.';
  }
}

/**
 * Health check for Gemini API
 */
export async function geminiHealthCheck(): Promise<boolean> {
  try {
    const generativeModel = vertex_ai.getGenerativeModel({ model });

    const result = await generativeModel.generateContent('Hello, respond with OK');
    const text = result.response.candidates?.[0]?.content?.parts?.[0]?.text || '';

    console.log('[Gemini] Health check passed');
    return text.toLowerCase().includes('ok');
  } catch (error) {
    console.error('[Gemini] Health check failed:', error);
    return false;
  }
}
